acme\sitioBundle\Entity\pagina:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: '30'
        contenido:
            type: string
            length: '100'
    manyToOne: 
        sitio:
            targetEntity: acme\sitioBundle\Entity\sitio
            inversedBy: pagina
     
        template:
            targetEntity: acme\sitioBundle\Entity\template
            inversedBy: pagina                        
    lifecycleCallbacks: {  }
