blog:
    path:     /
    defaults: { _controller: "sitioBundle:blog:index" }

blog_show:
    path:     /{id}/show
    defaults: { _controller: "sitioBundle:blog:show" }

blog_new:
    path:     /new
    defaults: { _controller: "sitioBundle:blog:new" }

blog_create:
    path:     /create
    defaults: { _controller: "sitioBundle:blog:create" }
    requirements: { _method: post }

blog_edit:
    path:     /{id}/edit
    defaults: { _controller: "sitioBundle:blog:edit" }

blog_update:
    path:     /{id}/update
    defaults: { _controller: "sitioBundle:blog:update" }
    requirements: { _method: post|put }

blog_delete:
    path:     /{id}/delete
    defaults: { _controller: "sitioBundle:blog:delete" }
    requirements: { _method: post|delete }
