pagina:
    path:     /
    defaults: { _controller: "sitioBundle:pagina:index" }

pagina_show:
    path:     /{id}/show
    defaults: { _controller: "sitioBundle:pagina:show" }

pagina_new:
    path:     /new
    defaults: { _controller: "sitioBundle:pagina:new" }

pagina_create:
    path:     /create
    defaults: { _controller: "sitioBundle:pagina:create" }
    requirements: { _method: post }

pagina_edit:
    path:     /{id}/edit
    defaults: { _controller: "sitioBundle:pagina:edit" }

pagina_update:
    path:     /{id}/update
    defaults: { _controller: "sitioBundle:pagina:update" }
    requirements: { _method: post|put }

pagina_delete:
    path:     /{id}/delete
    defaults: { _controller: "sitioBundle:pagina:delete" }
    requirements: { _method: post|delete }
