theme:
    path:     /
    defaults: { _controller: "sitioBundle:theme:index" }

theme_show:
    path:     /{id}/show
    defaults: { _controller: "sitioBundle:theme:show" }

theme_new:
    path:     /new
    defaults: { _controller: "sitioBundle:theme:new" }

theme_create:
    path:     /create
    defaults: { _controller: "sitioBundle:theme:create" }
    requirements: { _method: post }

theme_edit:
    path:     /{id}/edit
    defaults: { _controller: "sitioBundle:theme:edit" }

theme_update:
    path:     /{id}/update
    defaults: { _controller: "sitioBundle:theme:update" }
    requirements: { _method: post|put }

theme_delete:
    path:     /{id}/delete
    defaults: { _controller: "sitioBundle:theme:delete" }
    requirements: { _method: post|delete }
