widget:
    path:     /
    defaults: { _controller: "sitioBundle:widget:index" }

widget_show:
    path:     /{id}/show
    defaults: { _controller: "sitioBundle:widget:show" }

widget_new:
    path:     /new
    defaults: { _controller: "sitioBundle:widget:new" }

widget_create:
    path:     /create
    defaults: { _controller: "sitioBundle:widget:create" }
    requirements: { _method: post }

widget_edit:
    path:     /{id}/edit
    defaults: { _controller: "sitioBundle:widget:edit" }

widget_update:
    path:     /{id}/update
    defaults: { _controller: "sitioBundle:widget:update" }
    requirements: { _method: post|put }

widget_delete:
    path:     /{id}/delete
    defaults: { _controller: "sitioBundle:widget:delete" }
    requirements: { _method: post|delete }
